networks:
  trustfactory:

services:
  app:
    build:
      context: ./docker
      dockerfile: local/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      # - redis
      - mariadb
      - mailhog
    networks:
      - trustfactory

  mariadb:
    image: mariadb:11.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: trustfactory
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      # - ./docker-local/mysql:/var/lib/mysql
      - dbdata:/var/lib/mysql
    networks:
      - trustfactory

  php:
    build:
      context: ./docker
      dockerfile: local/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9010:9000"
    volumes:
      - ./:/var/www/html:delegated
    dns:
      - 10.11.8.253
      - 10.11.8.251
      - 161.53.123.13
      - 161.53.123.23
      - 161.53.195.43
    networks:
      - trustfactory

  #  redis:
  #    image: redis:alpine
  #    restart: unless-stopped
  #    ports:
  #      - "6379:6379"
  #    networks:
  #      - trustfactory

  composer:
    build:
      context: ./docker
      dockerfile: local/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - trustfactory

  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    command: [ 'run',  'dev' ]
    networks:
      - trustfactory

  artisan:
    build:
      context: ./docker
      dockerfile: local/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mariadb
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - trustfactory

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - trustfactory

volumes:
  dbdata:
